name: Build and deploy React frontend to Azure Web App - secure-rag-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React application
        working-directory: frontend
        env:
          VITE_API_URL: https://secure-rag-api-evf2fmcdfugzhqfw.southindia-01.azurewebsites.net
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./frontend-dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B87562F1C3E4E43AF97F2577CC1F718 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF17C61A3D164DD3B38AA64D5A019FBA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B1D3817EF7E4109B9D296C959DFD0C4 }}

      - name: Deploy React frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: secure-rag-frontend
          slot-name: Production
          package: ./frontend-dist