name: Build and deploy React frontend - secure-rag-frontend QA

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React application
        working-directory: frontend
        env:
          VITE_API_URL: https://secure-rag-api-qa-b9ajhcecfpbaeqe2.southindia-01.azurewebsites.net
                        
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA20ACEFFBDB4CE7BC450675EB5BD140 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A9C0DF4ED254E5CA38D0BB8589A380B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6D6ECFA4B8C4222A94033E2237B0168 }}

      - name: Deploy React frontend to QA slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: secure-rag-frontend
          slot-name: qa
          package: frontend-dist