name: Build and deploy React frontend - secure-rag-frontend UAT

on:
  push:
    branches:
      - uat
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React application
        working-directory: frontend
        env:
          VITE_API_URL: https://secure-rag-api-uat-h6g5g8ercwh2aeau.southindia-01.azurewebsites.net
                        
                        
        run: npm run build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4B87F3D863D549ADA3845FD387AE050A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_068CB53461F84B68A9C9346665B70743 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE703EA40650416DBA48EA3E218DC098 }}

      - name: Deploy React frontend to QA slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: secure-rag-frontend
          slot-name: uat
          package: frontend-dist